#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2019-2021 The Authors
#
# Licensed under the Raphielscape Public License, Version 1.d (the "License");
# you may not use this file except in compliance with the License.
#
# Telegram command container

TELEGRAM=$SEMAPHORE_PROJECT_DIR/init/telegramapi
export TELEGRAM
# Caster configurations
MAINGROUP_ID=""

# sendcast to group
tg_sendinfo() {
    "${TELEGRAM}" -c ${MAINGROUP_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

kickstart_pub() {
  if [ ! -z "$PULL_REQUEST_NUMBER" ]; then
     tg_sendinfo "I am starting build" \
     "PR: <code>${PULL_REQUEST_NUMBER}</code>" \
     "Commit Point <code>${COMMIT_POINT}</code>" \
     " " \
     "<b>Github Link: </b> https://github.com/Axdhu/SamuRai/commit/${COMMIT_HASH}" \
     " " \
     "<b>CI Link: </b> https://github.com/Axdhu/SamuRai"
  else
    tg_sendinfo "I am starting build" \
    "Branch <code>${PARSE_BRANCH}</code>" \
    "Commit Point <code>${COMMIT_POINT}</code>" \
    " " \
    "<b>Github Link: </b> https://github.com/Axdhu/SamuRai/commit/${COMMIT_HASH}" \
    " " \
    "<b>CI Link: </b> https://github.com/Axdhu/SamuRai"
fi
}
